### ISSUE TITLE
Not an issue: Works with AD410

### ISSUE THREAD

**Issue by jmorris644** [bmdevx/node-red-contrib-amcrest-ad110#3]
I just wanted to mention that your contrib seems to be working fine with the newer AD410. I am able to use the nodes as is for events that are common with the AD110 and use the raw for events such as human detection that are new.

One note, on the AD410 I am able to change the username. But as long as I keep it as 'admin' everything is fine.

Let me know if there is any interest in any enhancements you would like to see for the AD410.

One question, Where did you find the document describing the API for the AD110? I have yet to find a good source for the AD410 API.

**Comment by bmdevx** [comment]
Thanks. Glad it works with the AD410. I am planning on getting it eventually for testing although I have no plans on adding any enhancements currently. Video and audio streams through NodeRED is a bit tricky so those features have been placed on the back burned until I have more free time. I found the API as a pdf on the support form for Amcrest although it was mostly for their security cameras. For the next release I will put in the ability to change the username.
